changelog:
  - type: NEW_FEATURE
    description: flatten ratelimit config by creating v2 version of settings & route/virtual host extensions
    issueLink: https://github.com/solo-io/gloo/issues/1171
    resolvesIssue: false