apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloo-docs-{{ .Values.docsVersion }}
  labels:
    app: gloo-docs
    version: {{ .Values.docsVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: {{ .Values.docsVersion }}
  template:
    metadata:
      labels:
        app: gloo-docs
        version: {{ .Values.docsVersion }}
    spec:
      containers:
        - name: gloo-docs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
