apiVersion: v1
kind: Service
metadata:
  name: gloo-docs-{{ .Values.docsVersion }}
  labels:
    app: gloo-docs
    version: {{ .Values.docsVersion }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: {{ .Values.docsVersion }}
