# Configuration for make analyze
#
# For reference, consider:
#
# * https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
# * https://golangci-lint.run/usage/configuration/
#
linters:
  # Disable all linters.
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    # Given that we have not had linting enabled in this repository, it would be a large change to turn on all linters immediately.
    # We are aiming to progressively enable linters.
    # If you see a linter that can be added, please do so.
    # See: https://github.com/solo-io/gloo-mesh-enterprise/blob/main/.golangci.yaml for a reference
    - ginkgolinter

# Settings dedicated to specific linters.
linters-settings: {}

issues:
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  max-same-issues: 0

run:
  # Number of CPUs to use when running golangci-lint.
  # Default: the number of logical CPUs in the machine
  concurrency: 4

  # Include test files or not.
  tests: true

  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 5m

  skip-dirs:
    # don't lint ruleguard files
    - test/rules

    # don't lint gomock intermediate files
    - 'gomock_reflect_\d*'