sudo: required
language: go
go:
- 1.9.2
services:
- docker
env:
  matrix:
  - RUN_CONSUL_TESTS=1
  - RUN_NOMAD_TESTS=1
  - RUN_KUBE_TESTS=1
  - RUN_VAULT_TESTS=1
  - ENVOY_IMAGE_TAG=v0.1.6-127
  global:
  - secure: x6sWEdhvmobyFMZoSmReH0yrrFf8fBmMm2qgQW68hMdz+xmLUB0dUBytCDIJPT+n4DWES3twWdsE9Y6Lw5k8yDTnVOrk3nL0NIceIGQXe5R/StQFmkCYg45udyC3gNcSu5dxlGHgHyeVbVkhkdBU9kvLPp/2Z0YFUw0139DvKDG0sLGQO9MhXZN+V6Fs0jOFFqeraRi9cyRGKY3UwJ0s3upifIZJkZImtcGCX08RKV8KxrJuaC/4dB0d6/1wvY/6K8ipb5IEW2VDidcIV7lUSe5Hs9PtjMypa43LJwWoTkq6SeEhxfOhiTCCbTg5Q73CXFaHvhH7IwL31u0TxM+ujDcyVd7C01FvY6IWKOlGmIiMqbJOQzN7ieYB8znh1+qfUzUHUG3/JJCwrEWzlz16x6lODr6Ua55rhIC3tQ3Vbj8ON/8dyjLwhy50zRqnKiE+YP/xx2CPMK18cBAMh4EK/tufGwFmbjfvZNk31f9WBDnhiSrzWJM+aDUl/6dzJo6WjegQr+2ZD7m7d/IRF8r118juhPiOCF7NfIGYYrvESroMRQgWu/3xMw2NFGC07w3/e7UNt4p363K3BSbLdYk4Mf0bvTYoVF3oC9m/nVYOMxJmyVt5A9zC41+f0xjBa/CxVucnd1n/+ELqQiFwqGE/m7GZNOuOmOHp74u6NpRpi/U=
  - secure: DcF8KJoFb+MpHSfnlzAnaKYuvnjD3KlBbrloM016m/8U4pNRxgPlySaEmnUpLlnwyw6vChhplEopJYeRdO4L2vM7RRVJgYstjUOMuuQYHHAWkXDTUM5mJbfYkchIPogdHoMrxTjdqNRsV3EEzsJQg+c6ne4Z7MkC3a1OA3QCdOwBzyshqCWTPXLs0Sm0Y8dJISwQXts9g6emUIGei72V/2JXT/XflVzBZhDalS50642gdEyLhMzRxpnke5cPtHghMbw+4Hi4fVvzfpnv+L6I1nmPmZ9Q6w+YaVr26IwHdFSAYxEbN0BinUj7CONzXfFax2jNMSCNnZr/dSpn+932CkkVl1IydbxLomXyjNIJ+foRuUjP8dmNMlAIh29mYKMIsZV8NX18YoycAbSfRmOOSnRfXi1Hf3KCskZ6DaVBkXhV3NABDAWV/k5GldGur1Oi1IMysKCdkP+NdGcElbEyiaA7DbxgQLJLquhLxDgGKZx7Jh+xT0VZl6/9eg4OPgnyptF3B/77g6mx7lwranCXYal024N5HHhSjnlHrxaUROaaK5fwNpXw02Y/lUnJDM4FkRRzbFSqX5+DKDA8o5Yy4CSgU7kF++64+CpihiTUBW/sEIow2g5rQFYYFXDxYuHY4V9iXn1PMZoLp/ibWzCgkSfQTP5TbfgZhhZw9+5x6pE=
  - secure: fz6sbl/FqrV0Yvfu5wgSiHX4IniJTKamITUMt4S0qKwT/WYceVQKR5TknljTUB+u3sDDXuUlPhA6uM4vtbBawmjv4XGTDMu973wivbLT3nDPYJuIyT/ZtelO5fI9SNqjt/mI3ICqNjdLmxfTUyXxz/zOgokjQ1IwkcaZkLhDBUjYTP0EoLuWV9PaKqwOk9WEqjVaHP7JA4+jouNRSTgoJDXoWQtfb7J786Q4LhjNnTubUogbfkS7Ek/x+8MdMUVMM6luV69612cVHpW5Xi8c/nJe4Juq8eXwhWcfGga6k4GMINaAXQ0fF39Xu85K8g4tukGPPVZB/m8YKFy0wBEhUl9PIwqxI6+k/32IafzwusU8OTkUZ9bu3a8n7E1qqLXPGUkWDN446xm3ONRd/ThLvcurT+530/zZr6rI4ifI/wqqlSHsFrbRvGEcd3/eZkIY8HJq/BwtCEJkDVKOuRZkj2C5XgT5pj8k6CTS+oXg271An8DLqZIcTGygnoSdm5wu1OCRuSqZ/wYipbaYrgAxlrhNJr4Jf7tgtKr4kLXZbZkeqjvUi7+56d3ZVBMPNZxcLnU2qyF5NsvFw0ADiuY0QV7joOXf/12olWHekjyB2D7qulxtbsyHMhwDrvI/3auYStkuF4fDsK36PCwJnbg/7jNyp2T/ddYEYp2DGUdy4RQ=
  - secure: XRq4rfHA4RV1rXTFgqyVrBoJUO1tjio+VsSAfRvLOznxkaoOqghQBr5qL9dfI3jxb/jHpRiw6NvBLvCH7ZkH526bt3dlQ7T3TaGfuQ910584iTzUd2+J/9KkcIvS8zFcbN45PrN5DGIiSMxH+r63n4B/95QYt7YBLfNVJgPKdCet2xVa2ROabDuGVtK1nn1gMDoLJXX1FXdvMHCtWGWodyFteGPzH26FCauhY0kE+MQgA4ic9X669Bhi2wEH9wTGhUjGzB8kT3Ep+2hpJWEsLQWmGBZDHUbTstvY+TeZmVFL1SBzCizKs9jEy+oQnxWYTI71N9BwsQ8rE3rNgF+sFw8IuBYEzYWDG47kPUZoRorIE77TB60cbN9frq6zV6GIFcCUgvgorSU6nKFq72HdF4cOYUmenyuozgePBcZu6ZKi9sX6+Y8BQq0HuU7kB7/dwSftPiLtb/ibcZ5nzru7xJvj779Km8hyg1yYeZbR/Kx5Pi8GPtkdhwvFGgmsDZloqRFFxEU1PtlOmbiG0XTOGtdQ+TJGMlFkWq881v8nSEvrcoSHe9NlzJaXoQj0bhImPa60c9t6t/+/4RPHXKDv9x3/MA/CkbYnqgm8hlebSaLBLRUH350LP6isbp/cY88D0zlrrnZj4JOq6JNdsWPvbM0qzPqJeof78V/yhFT3AEk=
before_install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/onsi/ginkgo/ginkgo
- curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | sudo
  bash
dd:
- openssl aes-256-cbc -K $encrypted_a410bae03b49_key -iv $encrypted_a410bae03b49_iv
  -in config.enc -out ~\/.kube/config -d
before_script:
- cd ${GOPATH}/src/github.com/solo-io/gloo
- dep ensure -v
script: ginkgo -r -v .
