steps:

- name: 'gcr.io/$PROJECT_ID/prepare-go-workspace:0.6.1'
  args:
    - '--repo-name'
    - '$REPO_NAME'
    - '--repo-sha'
    - '$COMMIT_SHA'
    - '--repo-output-dir'
    - '.'
  env:
    - 'GIT_SSH_CONFIG=FALSE'
  id: 'prepare-workspace'

- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p /go/pkg && cd /go/pkg && gsutil cat gs://$PROJECT_ID-cache/gloo/gloo-mod.tar.gz | tar -xzf - || echo "untar mod cache failed; continuing because we can download deps as we need them"']
  id: 'untar-mod-cache'

# Overall build timeout of 60m.
timeout: '3600s'

tags:
- 'gloo'

options:
  machineType: 'N1_HIGHCPU_32'
  volumes:
    - name: 'gopath'
      path: '/go'