steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--config'
  - 'ci/cloudbuild/publish-artifacts.yaml'
  - '--substitutions'
  - 'COMMIT_SHA=$COMMIT_SHA,REPO_NAME=$REPO_NAME'
  waitFor:
  - '-'
  id: 'publish-artifacts'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'builds'
    - 'submit'
    - '--config'
    - 'ci/cloudbuild/run-tests.yaml'
    - '--substitutions'
    - 'COMMIT_SHA=$COMMIT_SHA,REPO_NAME=$REPO_NAME'
  waitFor:
    - '-'
  id: 'run-tests'

timeout: '3600s'

tags:
- 'gloo'

options:
  machineType: 'N1_HIGHCPU_32'
  env:
  - 'DOCKER_CONFIG=/workspace/docker-config'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'TEST_ASSET_ID=$_PR_NUM'