steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--config=cloudbuild-publish-artifacts.yaml'
  waitFor:
  - '-'
  id: 'publish-artifacts'

timeout: '3600s'

tags:
- 'gloo'

options:
  machineType: 'N1_HIGHCPU_32'
  env:
  - 'DOCKER_CONFIG=/workspace/docker-config'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'TEST_ASSET_ID=$_PR_NUM'