[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  version = ">=0.8.2"
  name = "github.com/envoyproxy/go-control-plane"

[[constraint]]
  version = "1.3.0"
  name = "github.com/gogo/protobuf"

[[override]]
  branch = "master"
  name = "k8s.io/api"

[[override]]
  version = "1.3.1"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/envoy-operator"
  version = "0.1.0"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.10.16"

[[override]]
  name = "github.com/solo-io/go-utils"
  version = "0.10.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.5.2"

[[constraint]]
  name = "github.com/solo-io/go-checkpoint"
  version = "0.1.0"

# make sure all kubernetes code is the same version.
# when updating, update all in the same time.

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.20.6"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/helm"
  version = "v2.12.3"

[[override]]
  name = "github.com/go-openapi/spec"
  version = "0.19.2"

[[constraint]]
  name = "knative.dev/serving"
  version = "v0.8.0"

# added to support knative v0.8.0
[[override]]
  name = "golang.org/x/net"
  revision = "aaf60122140d3fcf75376d319f0554393160eb50"

# added to support knative v0.8.0
[[override]]
  name = "golang.org/x/xerrors"
  revision = "a985d3407aa71f30cf86696ee0a2f409709f22e1"

[[override]]
  name = "k8s.io/klog"
  revision = "9cbb78b20423182f9e5b2a214dd255f5e117d2d1"
  source = "github.com/stefanprodan/klog"
