[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  revision = "676016db8193d83324a507a986a78cd3642ad713"
  name = "github.com/envoyproxy/go-control-plane"

[[constraint]]
  version = "1.1.1"
  name = "github.com/gogo/protobuf"

[[override]]
  branch = "master"
  name = "k8s.io/api"

[[override]]
  version = "1.2.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/envoy-operator"
  revision = "c71f318a203bca8433268be67336086379a2bf9f"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.2.12"

[[constraint]]
  name = "github.com/hashicorp/consul"
  revision = "eba25a143821cec25bdb48fe64dd7b7a6152d01d"

# go versioning story not ideal, so we have to pin serf to the version consul expects
[[override]]
  name = "github.com/hashicorp/serf"
  revision = "19bbd39e421bdf3559d5025fb2c760f5ffa56233"

[[constraint]]
  name = "github.com/solo-io/go-checkpoint"
  version = "0.0.4"

# TODO: avoid using revision here and use >= semver when go-utils has a release.
[[constraint]]
  name = "github.com/solo-io/go-utils"
  revision = "67428b92743fd710ab708665d5fff86e06ff1612"

# make sure all kubernetes code is the same version.
# when updating, update all in the same time.

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.0"