apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'www.example.com'
    routes:
      - matchers:
          - prefix: /productpage
        routeAction:
          single:
            upstream:
              name: default-productpage-9080
              namespace: gloo-system
