apiVersion: gateway.solo.io.v2/v2
kind: Gateway
metadata:
  annotations:
    origin: default
  name: gateway
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  gatewayProxyName: gateway-proxy-v2
  httpGateway: {}
  useProxyProto: false
  plugins:
    als:
      accessLog:
      - fileSink:
          path: /dev/stdout
          jsonFormat:
            protocol: "%PROTOCOL%"
            duration: "%DURATION%"