apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: gloo-system
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: jmalloc/echo-server
        ports:
        - containerPort: 8080
        env:
        - name: LOG_HTTP_HEADERS
          value: "true"
        - name: LOG_HTTP_BODY
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: gloo-system
  labels:
    app: echo-server
spec:
  ports:
  - name: echo-server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo-server