apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    gloo: proxycontroller
  name: proxycontroller
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: proxycontroller
  template:
    metadata:
      labels:
        gloo: proxycontroller
    spec:
      serviceAccountName: gloo # <- hijack the gloo service account rather than make a new one for this demo controller
      containers:
        - image: quay.io/solo-io/proxycontroller:1.2.12 # <- change this if you rebuild and push your controller to another registry
          imagePullPolicy: IfNotPresent
          name: proxycontroller