{{- if .Values.controlPlane.enabled -}}
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ .Values.gatewayClass.className }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName }}
{{- end }}