changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/solo-projects/issues/5909
    resolvesIssue: false
    description: >-
      Add new DataPlaneConfig CRD to allow configuration of dynamically provisioned proxies
      in Gloo Gateway.
