blank_issues_enabled: true
contact_links:
  - name: Talk with us on the CNCF Slack!
    url: https://slack.cncf.io/
    about: "We are in #k8sgateway channel!"
  - name: K8sGateway Documentation
    url: https://k8sgateway.io/docs/
    about: Check out the K8sGateway docs for helpful information.
