{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: gloo
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
{{- end}}