apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: ingress-proxy
  name: ingress-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.deployment.ingressProxy.httpPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.deployment.ingressProxy.httpsPort }}
    protocol: TCP
    name: https
  selector:
    gloo: ingress-proxy
  type: LoadBalancer
