{{- if .Values.settings.integrations.knative.enabled }}
# configmap
apiVersion: v1
data:
  envoy.yaml: |
    node:
      cluster: clusteringress
      id: "{{ "{{" }}.PodName{{ "}}" }}.{{ "{{" }}.PodNamespace{{ "}}" }}"
      metadata:
        # this line must match !
        role: "{{ .Release.Namespace }}~clusteringress-proxy"
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 5.000s
        load_assignment:
          cluster_name: xds_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: gloo
                    port_value: {{ .Values.deployment.gloo.xdsPort }}
        http2_protocol_options: {}
        type: STRICT_DNS
    dynamic_resources:
      ads_config:
        api_type: GRPC
        grpc_services:
        - envoy_grpc: {cluster_name: xds_cluster}
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 19000
kind: ConfigMap
metadata:
  labels:
    app: gloo
  name: clusteringress-envoy-config
  namespace: {{ .Release.Namespace }}
{{- end }}