{{ define "gloo.serviceAccountSpec"}}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.gloo.serviceAccount.extraAnnotations }}
  annotations:
    {{- range $key, $value := .Values.gloo.serviceAccount.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app: gloo
    gloo: gloo
  name: gloo
  namespace: {{ $.Release.Namespace }}
{{- if .Values.gloo.serviceAccount.disableAutomount }}
automountServiceAccountToken: false
{{ end }}
{{- end }} {{/* define "gloo.serviceAccountSpec "*/}}

{{/* Render template with yaml overrides */}}
{{- $yamlOverride := (dict ) | toYaml -}}
{{- if .Values.gloo.serviceAccount -}}
{{- if .Values.gloo.serviceAccount.yamlOverride -}}
{{- $yamlOverride = .Values.gloo.serviceAccount.yamlOverride | toYaml -}}
{{- end -}}
{{- end -}}
{{- template "gloo.util.merge" (list . $yamlOverride "gloo.serviceAccountSpec") -}}
