{{- if .Values.rbac.create }}

{{- if .Values.gateway.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role-binding-gateway-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-role-gateway
  apiGroup: rbac.authorization.k8s.io

---
{{- end -}}

{{- if .Values.ingress.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role-binding-ingress-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-role-ingress
  apiGroup: rbac.authorization.k8s.io

---
{{- end -}}

{{- if .Values.settings.integrations.knative.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role-binding-knative-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-role-knative
  apiGroup: rbac.authorization.k8s.io

---
{{- end -}}

{{- end -}}
