{{- if .Values.global.glooRbac.create }}
{{- if .Values.gateway.enabled }}
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-resource-watcher-binding{{ include "gloo.rolebindingsuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "15"
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: discovery
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: kube-resource-watcher
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-upstream-mutator-binding{{ include "gloo.rolebindingsuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "15"
subjects:
- kind: ServiceAccount
  name: discovery
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-upstream-mutator
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-reader-binding{{ include "gloo.rolebindingsuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "15"
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-resource-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: settings-user-binding{{ include "gloo.rolebindingsuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "15"
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: gateway
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: discovery
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: settings-user
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-mutator-binding{{ include "gloo.rolebindingsuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "15"
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-resource-mutator
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gateway-resource-reader-binding{{ include "gloo.rolebindingsuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "15"
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gateway-resource-reader
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}
