{{- define "discovery.serviceAccountSpec"}}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.discovery.serviceAccount.extraAnnotations }}
  annotations:
    {{- range $key, $value := .Values.discovery.serviceAccount.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app: gloo
    gloo: discovery
  name: discovery
  namespace: {{ $.Release.Namespace }}
{{- if .Values.discovery.serviceAccount.disableAutomount }}
automountServiceAccountToken: false
{{ end }}
{{- end }}

{{/* Render template with yaml overrides */}}
{{- $yamlOverride := (dict ) | toYaml -}}
{{- if .Values.discovery.serviceAccount -}}
{{- if .Values.discovery.serviceAccount.yamlOverride -}}
{{- $yamlOverride = .Values.discovery.serviceAccount.yamlOverride | toYaml -}}
{{- end -}}
{{- end -}}
{{- template "gloo.util.merge" (list . $yamlOverride "discovery.serviceAccountSpec") -}}