{{- if .Values.apiServer.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: {{ .Values.apiServer.service.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
  name: {{ .Values.apiServer.service.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }} # .Values.apiServer.enable
