{{- if .Values.kubeGateway.enabled -}}
kind: GatewayParameters
apiVersion: gateway.gloo.solo.io/v1alpha1
metadata:
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
  name: default
spec:
  # TODO(jbohanon)
{{- end }}{{/* if .Values.kubeGateway.enabled */}}
