{{- if .Values.kubeGateway.enabled -}}
kind: GatewayParameters
apiVersion: gateway.gloo.solo.io/v1alpha1
metadata:
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
  name: default
  namespace: default
{{- if .Values.kubeGateway.defaultGatewayParameters }}
spec:
  kube:
{{- toYaml .Values.kubeGateway.defaultGatewayParameters | nindent 4 -}}
{{- end -}}{{/* if .Values.kubeGateway.defaultGatewayParameters */}}
{{- end }}{{/* if .Values.kubeGateway.enabled */}}
