{{- if and .Values.gateway.enabled .Values.gateway.validation.enabled .Values.gateway.validation.webhook.enabled (eq .Values.gateway.validation.failurePolicy "Fail") }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: gateway
  name: gloo-gateway-rollout
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      labels:
        gloo: gateway
    spec:
      serviceAccountName: gloo-gateway-rollout
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.22.9
          imagePullPolicy: "IfNotPresent"
          command:
          - /bin/sh
          - -c
          - "kubectl rollout status deployment -n {{ .Release.Namespace }} gateway --timeout=2m || true"
      restartPolicy: Never
---
{{- if .Values.global.glooRbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
  name: gloo-gateway-rollout
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-gateway-rollout
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-gateway-rollout
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
roleRef:
  kind: Role
  name: gloo-gateway-rollout
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gloo-gateway-rollout
  namespace: {{ .Release.Namespace }}

{{- end }} {{/* .Values.global.glooRbac.create */}}
{{- end }} {{/* if and .Values.gateway.enabled .Values.gateway.validation.enabled .Values.gateway.validation.webhook.enabled (eq .Values.gateway.validation.failurePolicy "Fail") */}}
