{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: gateway
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
  name: gateway
  namespace: {{ $.Release.Namespace }}


{{- if .Values.gateway.validation }}
{{- if .Values.gateway.certGenJob }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: gateway
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
  name: gateway-certgen
  namespace: {{ $.Release.Namespace }}
{{ end }}
{{ end }}

{{ end }}
