{{- $image := .Values.gateway.rolloutJob.image }}
{{- if .Values.global }}
{{- $image = merge .Values.gateway.rolloutJob.image .Values.global.image }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: resource-migration
  name: gloo-resource-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "3" # run this job after the role/rolebinding is created, and before the validation webhook is upgraded
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        gloo: resource-migration
    spec:
      {{- include "gloo.pullSecret" $image | nindent 6 -}}
      serviceAccountName: gloo-resource-migration
      containers:
        - name: kubectl
          image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ $image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            {{- if not .Values.gateway.rolloutJob.floatingUserId }}
            runAsUser: {{ printf "%.0f" (float64 .Values.gateway.rolloutJob.runAsUser) -}}
            {{- end }}
          command:
          - /bin/sh
          - -c
          - |
            # remove existing helm labels/annotations since the custom resources are no longer managed by helm
            {{- range list "helm.sh/hook" "helm.sh/hook-weight" "meta.helm.sh/release-name" "meta.helm.sh/release-namespace" }}
            kubectl annotate upstreams.gloo.solo.io -n {{ $.Release.Namespace }} -l created_by=gloo-install {{ . }}- || exit $?
            {{- end }}
            kubectl label upstreams.gloo.solo.io -n {{ $.Release.Namespace }} -l created_by=gloo-install,app.kubernetes.io/managed-by=Helm app.kubernetes.io/managed-by- || exit $?

            # gateways can be in multiple namespaces
            {{- range include "gloo.gatewayNamespaces" $ | fromJsonArray }}
            {{- $ns := . -}}
            {{- range list "helm.sh/hook" "helm.sh/hook-weight" "meta.helm.sh/release-name" "meta.helm.sh/release-namespace" }}
            kubectl annotate gateways.gateway.solo.io -n {{ $ns }} -l created_by=gloo-install {{ . }}- || exit $?
            {{- end }}{{/* range list helm annotations */}}
            kubectl label gateways.gateway.solo.io -n {{ $ns }} -l created_by=gloo-install,app.kubernetes.io/managed-by=Helm app.kubernetes.io/managed-by- || exit $?
            {{- end }}{{/* range namespaces */}}
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 0
{{- if .Values.global.glooRbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0" # must be created before job
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  name: gloo-resource-migration
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-migration
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0" # must be created before job
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
- apiGroups: ["gateway.solo.io"]
  resources: ["*"]
  verbs: ["get", "list", "update", "patch"]
- apiGroups: ["gloo.solo.io"]
  resources: ["*"]
  verbs: ["get", "list", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-migration
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0" # must be created before job
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  kind: Role
  name: gloo-resource-migration
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gloo-resource-migration
  namespace: {{ .Release.Namespace }}
{{- end }}{{/* if .Values.global.glooRbac.create */}}
