{{- if .Values.gateway.enabled }}
{{- if .Values.accessLogger }}
{{ $serverPort := 8083 }}
{{- if .Values.accessLogger.port }}
{{ $serverPort := .Values.accessLogger.port }}
{{- end}} # if .Values.accessLogger.port
{{- $image := .Values.accessLogger.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.accessLogger.image .Values.global.image }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy-v2-access-logger
  name: gateway-proxy-v2-access-logger
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ .Values.accessLogger.replicas }}
  selector:
    matchLabels:
      app: gloo
      gloo: gateway-proxy-v2-access-logger
  template:
    metadata:
      labels:
        app: gloo
        gloo: gateway-proxy-v2-access-logger
    spec:
      serviceAccountName: gateway-proxy
      containers:
        - image: {{ template "gloo.image" $image }}
          imagePullPolicy: {{ $image.pullPolicy }}
          name: access-logger
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
{{- if .Values.accessLogger.serviceName }}
          - name: SERVICE_NAME
            value: {{.Values.accessLogger.serviceName}}
{{- end }} # if .Values.accessLogger.serviceName
          - name: SERVER_PORT
            value: "{{ $serverPort }}"
          ports:
          - containerPort: {{ $serverPort }}
            name: http
            protocol: TCP
{{- end }} # if .Values.accessLogger
{{- end }} # if .Values.gateway.enabled