{{- if .Values.gateway.enabled }}
{{- range $name, $spec := .Values.gatewayProxies }}
{{- if $spec.accessLogger }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy-access-logger
    gateway-proxy-id: {{ $name | kebabcase }}
  name: {{ $name | kebabcase }}-access-logger
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - port: {{ $spec.service.httpPort }}
    targetPort: {{ $spec.podTemplate.httpPort }}
    protocol: TCP
    name: http
  selector:
    gateway-proxy-id: {{ $name | kebabcase }}
{{- end }} # if $spec.accessLogger
{{- end }} # range $name, $spec := .Values.gatewayProxies
{{ end }} # if .Values.gateway.enabled
