{{- define "accessLogger.serviceSpec"}}
{{- if and .Values.gateway.enabled .Values.accessLogger.enabled }}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy-access-logger
  name: gateway-proxy-access-logger
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.accessLogger.port }}
    targetPort: {{ .Values.accessLogger.port }}
    protocol: TCP
    name: http
  selector:
    app: gloo
    gloo: gateway-proxy-access-logger
{{- end }} {{/* if and .Values.gateway.enabled .Values.accessLogger.enabled */}}
{{- end }} {{/* define "accessLogger.serviceSpec" */}}

{{/* Render template with yaml overrides */}}
{{- $yamlOverride := dict -}}
{{- if .Values.accessLogger.service -}}
{{- $yamlOverride = .Values.accessLogger.service.yamlOverride  -}}
{{- end -}}
{{- include "gloo.util.merge" (list . $yamlOverride "accessLogger.serviceSpec") -}}