{{- if or (and .Values.gateway.enabled .Values.gateway.validation.enabled .Values.gateway.certGenJob.enabled) (.Values.global.glooMtls.enabled) }}
---
{{- if .Values.global.glooRbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5" # must be executed before cert-gen job
  name: certgen
  namespace: {{ $.Release.Namespace }}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-gateway-vwc-update{{ include "gloo.rbacNameSuffix" . }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5" # must be executed before cert-gen job
subjects:
- kind: ServiceAccount
  name: certgen
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-gateway-vwc-update{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io

---

kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-gateway-secret-create{{ include "gloo.rbacNameSuffix" . }}
  {{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5" # must be executed before cert-gen job
subjects:
  - kind: ServiceAccount
    name: certgen
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-gateway-secret-create{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-gateway-vwc-update{{ include "gloo.rbacNameSuffix" . }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5" # must be executed before cert-gen job
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "update"]

---

kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-gateway-secret-create{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5" # must be executed before cert-gen job
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update"]

---

{{- end }} {{/* .Values.global.glooRbac.create */}}
{{- end }} {{/* {{- if or (and gateway.enabled validation.enabled certGenJob.enabled glooMtls.enabled */}}
