{{- if .Values.gateway.enabled }}
{{- if .Values.gateway.upgrade }}
{{- $image := .Values.gateway.conversionJob.image }}
{{- if .Values.global  }}
{{- $image = mergeOverwrite .Values.global.image .Values.gateway.conversionJob.image }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: gateway
  name: gateway-conversion
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        gloo: gateway
    spec:
      containers:
        - image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ $image.pullPolicy }}
          name: gateway-conversion
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: {{ .Values.gateway.conversionJob.restartPolicy }}
{{- end }}
{{- end }}