{{- if .Values.gateway.enabled }}
{{- range $name, $spec := .Values.gatewayProxies }}
{{- if $spec.kind.deployment}}
{{- if $spec.hpa.enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: {{ $name | kebabcase }}
  name: {{ $name | kebabcase }}
  namespace: {{ $.Release.Namespace }}
spec:
  maxReplicas: {{ $spec.hpa.maxReplicas }}
  minReplicas: {{ $spec.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ $name | kebabcase }}
  targetCPUUtilizationPercentage: {{ $spec.hpa.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}