apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.gatewayProxy.replicas }}
  selector:
    matchLabels:
      gloo: gateway-proxy
  template:
    metadata:
      labels:
        gloo: gateway-proxy
    spec:
      containers:
      - args: ["--disable-hot-restart"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.deployment.gatewayProxy.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        name: gateway-proxy
        ports:
        - containerPort: {{ .Values.deployment.gatewayProxy.httpPort }}
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
{{- with .Values.deployment.gloo.imagePullSecrets }}
      imagePullSecrets:
{{toYaml . | indent 6}}
{{end}}
      volumes:
      - configMap:
          name: gateway-envoy-config
        name: envoy-config