{{- range $name, $spec := .Values.gatewayProxies }}
{{- if not $spec.disableGeneratedGateways}}
apiVersion: v1
kind: List
metadata:
  labels:
    app: gloo
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
items:
 - apiVersion: gateway.solo.io.v2/v2
   kind: Gateway
   metadata:
     name: {{ $name | kebabcase }}
     namespace: {{ $.Release.Namespace }}
     labels:
       app: gloo
   spec:
     bindAddress: "{{ $spec.httpListenAddress }}"
     bindPort: {{ $spec.podTemplate.httpPort }}
     gatewayProxyName: {{ $spec.proxyName }}
     httpGateway: {}
     useProxyProto: {{ $spec.useProxyProto }}
     ssl: false
     proxyNames:
       - {{ $name | kebabcase }}
 - apiVersion: gateway.solo.io.v2/v2
   kind: Gateway
   metadata:
     name: {{ $name | kebabcase }}-ssl
     namespace: {{ $.Release.Namespace }}
     labels:
       app: gloo
   spec:
     bindAddress: "{{ $spec.httpListenAddress }}"
     bindPort: {{ $spec.podTemplate.httpsPort }}
     gatewayProxyName: {{ $spec.proxyName }}
     httpGateway: {}
     useProxyProto: {{ $spec.useProxyProto }}
     ssl: true
     proxyNames:
       - {{ $name | kebabcase }}
{{- end }}
{{- end }}