{{- range $name, $spec := .Values.gatewayProxies }}
{{- if $spec.gatewaySettings}}
{{$gatewaySettings := $spec.gatewaySettings}}
{{- if not $gatewaySettings.disableGeneratedGateways}}

---
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: {{ $name | kebabcase }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: gloo
spec:
  bindAddress: "::"
  bindPort: {{ $spec.podTemplate.httpPort }}
{{- if $gatewaySettings.customHttpGateway}}
  httpGateway:
{{ toYaml $gatewaySettings.customHttpGateway | indent 4}}
{{- else }}
  httpGateway: {}
{{- end }}
  useProxyProto: {{ $gatewaySettings.useProxyProto }}
  ssl: false
  proxyNames:
{{- if $gatewaySettings.customProxyNames }}
{{ toYaml $gatewaySettings.customProxyNames | indent 2 }}
{{- else }}
  - {{ $name | kebabcase }}
{{- end }}

---

apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: {{ $name | kebabcase }}-ssl
  namespace: {{ $.Release.Namespace }}
  labels:
    app: gloo
spec:
  bindAddress: "::"
  bindPort: {{ $spec.podTemplate.httpsPort }}
{{- if $gatewaySettings.customHttpsGateway}}
  httpGateway:
{{ toYaml $gatewaySettings.customHttpsGateway | indent 4}}
{{- else }}
  httpGateway: {}
{{- end }}
  useProxyProto: {{ $gatewaySettings.useProxyProto }}
  ssl: true
  proxyNames:
{{- if $gatewaySettings.customProxyNames }}
{{ toYaml $gatewaySettings.customProxyNames | indent 2 }}
{{- else }}
  - {{ $name | kebabcase }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
