{{- define "gateway.proxyServiceAccountSpec" }}
{{- $gatewayNs := (index . 1) }}
{{- with (first .) }}
{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.gateway.proxyServiceAccount.extraAnnotations }}
  annotations:
    {{- range $key, $value := .Values.gateway.proxyServiceAccount.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app: gloo
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: {{ $gatewayNs }}
{{- if .Values.gateway.proxyServiceAccount.disableAutomount }}
automountServiceAccountToken: false
{{ end }}
{{ end }}
{{- end }}
{{- end }}

{{- $kubeResourceOverride := dict -}}
{{- if .Values.gateway -}}
{{- if .Values.gateway.proxyServiceAccount -}}
{{- $kubeResourceOverride = .Values.gateway.proxyServiceAccount.kubeResourceOverride  -}}
{{- end -}}
{{- end -}}

{{- $proxyNamespaces := list -}}
{{- range $key, $gatewaySpec := .Values.gatewayProxies -}}
  {{- $ns := $gatewaySpec.namespace | default $.Release.Namespace -}}
  {{- $proxyNamespaces = append $proxyNamespaces $ns -}}
{{- end -}}
{{- $proxyNamespaces = $proxyNamespaces | uniq -}}

{{- range $ns := $proxyNamespaces}}
{{- $ctx := (list $ $ns) }}
---
{{- include "gloo.util.merge" (list $ctx ($kubeResourceOverride ) "gateway.proxyServiceAccountSpec") -}}
{{- end }}