{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.gatewayProxy.deployment.httpPort }}
    protocol: TCP
    name: http
  selector:
    gloo: gateway-proxy
  type: LoadBalancer

{{- end }}