{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.gatewayProxy.service.httpPort }}
    targetPort: {{ .Values.gatewayProxy.deployment.httpPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.gatewayProxy.service.httpsPort }}
    targetPort: {{ .Values.gatewayProxy.deployment.httpsPort }}
    protocol: TCP
    name: https
  selector:
    gloo: gateway-proxy
  type: {{ .Values.gatewayProxy.service.type }}

{{- end }}