apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: blue-upstream
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /health
    interval: 1s
    noTrafficInterval: 1s
    timeout: 1s
    unhealthyThreshold: 1
  kube:
    selector:
      app: bluegreen
      text: blue
    serviceName: service-blue
    serviceNamespace: default
    servicePort: 10000
