apiVersion: fed.solo.io/v1
kind: FailoverScheme
metadata:
  name: failover-test-scheme
  namespace: gloo-fed
spec:
  primary:
    clusterName: kind-local
    name: default-service-blue
    namespace: gloo-system
  failoverGroups:
  - priorityGroup:
    - cluster: kind-remote
      upstreams:
      - name: default-service-green-10000
        namespace: gloo-system