changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo/issues/3329
    resolvesIssue: false
    description: >
      Allow direct specification of a config map with mod security ruleset to allow for dynamic loading of customer specified rulesets