# Default values for gloo-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

develop: false

gateway:
  enabled: false
  nameOverride: ""
  fullnameOverride: ""
  gatewayName: ""
  xds:
    host: ""
    port: 8080
  replicaCount: 1
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  service:
    type: ClusterIP
  readinessPort: 8082
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  image:
    repository: quay.io/solo-io/gloo-envoy-wrapper
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  istioSDS:
    enabled: false
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10101
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
