namespace:
  create: true
rbac:
  create: true

settings:
  # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
  watchNamespaces:
    - "gloo-system"
    - "default"
  # the namespace that Gloo should write discovery data (Upstreams)
  writeNamespace: "gloo-system"

deployment:
  imagePullPolicy: Always
  gloo:
    xdsPort: 9977
    image: soloio/gloo:0.5.0
    replicas: 1
  discovery:
    image: soloio/discovery:0.5.0
    replicas: 1
  gateway:
    image: soloio/gateway:0.5.0
    replicas: 1
  gatewayProxy:
    image: soloio/gloo-envoy-wrapper:0.5.0
    httpPort: 8080
    replicas: 1
  ingress:
    image: soloio/ingress:0.5.0
    replicas: 1
  ingressProxy:
    image: soloio/gloo-envoy-wrapper:0.5.0
    httpPort: 80
    replicas: 1
