namespace:
  create: false
crds:
  create: true
k8s:
  clusterName: cluster.local

settings:
  # if this is set to false, default settings will be created by pods upon boot
  create: false
  integrations:
    knative:
      enabled: false
  # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
  watchNamespaces: []

gloo:
  deployment:
    image:
      repository: gloo
    xdsPort: 9977
    replicas: 1
    stats: true

discovery:
  enabled: true
  deployment:
    image:
      repository: discovery
    replicas: 1
    stats: true

apiServer:
  enable: true
  enableBeta: true
  deployment:
    stats: true
    name: "grpcserver-ui"
    server:
      image:
        name: apiserver
        repository: grpcserver-ee
      grpcPort: 10101
      oauth: {}
    ui:
      image:
        name: "gloo-ui"
        repository: grpcserver-ui
      staticPort: 8080
    envoy:
      image:
        name: "grpcserver-envoy"
        repository: grpcserver-envoy
  service:
    name: "apiserver-ui"

gateway:
  enabled: true
  upgrade: false
  deployment:
    image:
      repository: gateway
    replicas: 1
    stats: true
  conversionJob:
    image:
      repository: gateway-conversion
    restartPolicy: Never
  proxyServiceAccount: {}
gatewayProxies:
  gatewayProxyV2:
    stats: true
    kind:
       deployment:
         replicas: 1
    podTemplate:
      probes: false
      image:
        repository: gloo-envoy-wrapper
      httpPort: 8080
      httpsPort: 8443
    service:
      type: LoadBalancer
      # clusterIP: None
      httpPort: 80
      httpsPort: 443
    # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
    # extraAnnotations:
    #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT
    tracing:
    configMap:
      data:

accessLogger:
  enabled: false
  port: 8083
  serviceName: AccessLog
  image:
    repository: access-logger
  replicas: 1

ingress:
  enabled: false

global:
  image:
    registry: quay.io/solo-io
    pullPolicy: IfNotPresent
  glooRbac:
    create: true