namespace:
  create: false
rbac:
  create: true

settings:
  # if this is set to false, default settings will be created by pods upon boot
  create: false
  integrations:
    knative:
      enabled: false
  # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
  watchNamespaces: []
  # the namespace that Gloo should write discovery data (Upstreams)
  writeNamespace: "gloo-system"

gloo:
  deployment:
    image:
      repository: soloio/gloo
      pullPolicy: Always
    xdsPort: 9977
    replicas: 1

discovery:
  deployment:
    image:
      repository: soloio/discovery
      pullPolicy: Always
    replicas: 1

gateway:
  enabled: true
  deployment:
    image:
      repository: soloio/gateway
      pullPolicy: Always
    replicas: 1

gatewayProxy:
  deployment:
    image:
      repository: soloio/gloo-envoy-wrapper
      pullPolicy: Always
    httpPort: 8080
    httpsPort: 8443
    replicas: 1
  service:
    type: LoadBalancer
    httpPort: 80
    httpsPort: 443
  configMap:
    data:


ingress:
  enabled: false