settings:
  integrations:
    knative:
      enabled: true
      proxy:
        image:
          repository: soloio/gloo-envoy-wrapper
          pullPolicy: Always
        httpPort: 80
        httpsPort: 443
        replicas: 1

gateway:
  enabled: false

ingress:
  enabled: false

