namespace:
  create: false
rbac:
  create: true
crds:
  create: true
k8s:
  clusterName: cluster.local

ingress:
  enabled: true
  deployment:
    image:
      repository: quay.io/solo-io/ingress
      pullPolicy: Always
    replicas: 1


ingressProxy:
  deployment:
    image:
      repository: quay.io/solo-io/gloo-envoy-wrapper
      pullPolicy: Always
    httpPort: 80
    httpsPort: 443
    replicas: 1
  configMap:
    data:

gateway:
  enabled: false
