namespace:
  create: false

ingress:
  enabled: true
  deployment:
    image:
      repository: soloio/ingress
      pullPolicy: Always
    replicas: 1


ingressProxy:
  deployment:
    image:
      repository: soloio/gloo-envoy-wrapper
      pullPolicy: Always
    httpPort: 80
    httpsPort: 443
    replicas: 1
  configMap:
    data:

gateway:
  enabled: false
