namespace:
  create: false
rbac:
  create: true
crds:
  create: true
k8s:
  clusterName: cluster.local

ingress:
  enabled: true
  deployment:
    image:
      repository: ingress
    replicas: 1


ingressProxy:
  deployment:
    image:
      repository: gloo-envoy-wrapper
    httpPort: 80
    httpsPort: 443
    replicas: 1
    stats: true
  configMap:
    data:
  tracing:

gateway:
  enabled: false

global:
  image:
    registry: quay.io/solo-ioxs
    pullPolicy: IfNotPresent

