namespace:
  create: false
rbac:
  create: true
crds:
  create: true
k8s:
  clusterName: cluster.local

settings:
  # if this is set to false, default settings will be created by pods upon boot
  create: false
  integrations:
    knative:
      enabled: false
  # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
  watchNamespaces: []
  # the namespace that Gloo should write discovery data (Upstreams)
  writeNamespace: "gloo-system"

gloo:
  deployment:
    image:
      repository: gloo
    xdsPort: 9977
    replicas: 1
    stats: true

discovery:
  deployment:
    image:
      repository: discovery
    replicas: 1
    stats: true

gateway:
  enabled: true
  upgrade: false
  deployment:
    image:
      repository: gateway
    replicas: 1
    stats: true
  conversionJob:
    image:
      repository: gateway-conversion
    restartPolicy: Never

gatewayProxies:
  gatewayProxyV2:
    kind:
       deployment:
         replicas: 1
    podTemplate:
      probes: false
      image:
        repository: gloo-envoy-wrapper
      stats: true
      httpPort: 8080
      httpsPort: 8443
    service:
      type: LoadBalancer
      # clusterIP: None
      httpPort: 80
      httpsPort: 443
    # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
    # extraAnnotations:
    #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT
    tracing:
    configMap:
      data:


ingress:
  enabled: false

global:
  image:
    registry: quay.io/solo-io
    pullPolicy: IfNotPresent
