changelog:
  - type: HELM
    description: >
      Move pod-level options outside of container configuration in gateway-proxy's Helm template.
    issueLink: https://github.com/solo-io/gloo/issues/5604