```yaml
rateLimits:
  # generate descriptors for Rule 1 and 2
  - actions:
      - requestHeaders:
          descriptorKey: type
          headerName: x-type
  # generate descriptors for Rule 3
  - actions:
      - requestHeaders:
          descriptorKey: type
          headerName: x-type
      - requestHeaders:
          descriptorKey: number
          headerName: x-number
```