---
apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-latest
  labels:
    app: gloo-docs
    version: latest
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-latest
  labels:
    app: gloo-docs
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: latest
  template:
    metadata:
      labels:
        app: gloo-docs
        version: latest
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:current"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-1-3-0
  labels:
    app: gloo-docs
    version: 1-3-0
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: 1-3-0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-1-3-0
  labels:
    app: gloo-docs
    version: 1-3-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: 1-3-0
  template:
    metadata:
      labels:
        app: gloo-docs
        version: 1-3-0
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:1.3.0"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-1-2-0
  labels:
    app: gloo-docs
    version: 1-2-0
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: 1-2-0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-1-2-0
  labels:
    app: gloo-docs
    version: 1-2-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: 1-2-0
  template:
    metadata:
      labels:
        app: gloo-docs
        version: 1-2-0
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:1.2.0"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: docsmgmt
  namespace: docs
spec:
  displayName: docsmgmt
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /gloo/latest
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-latest-80
            namespace: gloo-system
    - matchers:
      - prefix: /gloo/1.3.0/
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-1-3-0-80
            namespace: gloo-system
    - matchers:
      - prefix: /gloo/1.2.0/
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-1-2-0-80
            namespace: gloo-system
