changelog:
  - type: NON_USER_FACING
    description: >
      This is a change to a template that only changes if you enable the
      readConfigMulticluster helm value. Instead of creating a default
      gateway-proxy-config-dump-service, create a service named
      [gateway-proxy-name]-config-dump-service.