name: Kubernetes End-to-End tests

# These tests are located in the /test/kubernetes/e2e directory
description: Kubernetes End-to-End tests

inputs:
  cluster-name:
    required: true
    description: The name of the KinD cluster
  test-args:
    required: true
    description: The list of arguments passed to the test invocation
  run-regex:
    required: true
    # In the future, it would be preferable to accept this as a list of strings
    # and to then build the regex from that list
    description: The regex passed to the test invocation with the -run flag

runs:
  using: "composite"
  steps:
  - name: Install test tools
    shell: bash
    run: make install-test-tools
  - name: Execute tests
    env:
      GO_TEST_USER_ARGS: ${{ inputs.test-args }} -run ${{ inputs.run-regex }}
      CLUSTER_NAME: ${{ inputs.cluster-name }}
      TEST_PKG: ./test/kubernetes/e2e/...
    shell: bash
    run: make go-test
  # TODO: Emit artifacts to shared location on failure