name: Kubernetes End-to-End tests

# These tests are located in the /test/kubernetes/e2e directory
description: Kubernetes End-to-End tests

inputs:
  cluster-name:
    required: true
    description: The name of the KinD cluster
  test-args:
    required: true
    description: The list of arguments passed to the test invocation

runs:
  using: "composite"
  steps:
  - name: Install test tools
    shell: bash
    run: make install-test-tools
  - name: Execute tests
    env:
      # We intentionally set an upper threshold of 25 minutes for our End-to-End tests
      # Our goal is to load balance tests in a way that allows quick iteration on PRs
      # If tests are exceeding the 25-minute limit, please see:
      # /test/kubernetes/e2e/load_balancing_tests.md
      GO_TEST_USER_ARGS: ${{ inputs.test-args }} -timeout=25m
      CLUSTER_NAME: ${{ inputs.cluster-name }}
      TEST_PKG: ./test/kubernetes/e2e/tests
    shell: bash
    run: make go-test
    ## We want to move all tests into the /tests directory
    ## In the meantime, we rely on defining multiple packages where the tests are defined
  - name: Execute tests (k8sgateway)
    env:
      # We intentionally set an upper threshold of 25 minutes for our End-to-End tests
      # Our goal is to load balance tests in a way that allows quick iteration on PRs
      # If tests are exceeding the 25-minute limit, please see:
      # /test/kubernetes/e2e/load_balancing_tests.md
      GO_TEST_USER_ARGS: ${{ inputs.test-args }} -timeout=25m
      CLUSTER_NAME: ${{ inputs.cluster-name }}
      ## We want to move all tests into the /tests directory
      ## In the meantime, we rely on defining multiple packages where the tests are defined
      TEST_PKG: ./test/kubernetes/e2e/k8sgateway
    shell: bash
    run: make go-test
  # TODO: Emit artifacts to shared location on failure