name: Kubernetes End-to-End tests

# These tests are located in the /test/kubernetes/e2e directory
description: Kubernetes End-to-End tests

inputs:
  cluster-name:
    required: true
    description: The name of the KinD cluster
  test-args:
    required: true
    description: The list of arguments passed to the test invocation

runs:
  using: "composite"
  steps:
  - name: Install test tools
    shell: bash
    run: make install-test-tools
  - name: Execute tests
    env:
      GO_TEST_USER_ARGS: ${{ inputs.test-args }}
      CLUSTER_NAME: ${{ inputs.cluster-name }}
      ## We want to move all tests into the /tests directory
      ## In the meantime, we rely on defining multiple packages where the tests are defined
      TEST_PKG: test/kubernetes/e2e/tests,test/kubernetes/e2e/k8sgateway
    shell: bash
    run: make go-test
  # TODO: Emit artifacts to shared location on failure