changelog:
  - type: NEW_FEATURE
    description: Solves part of https://github.com/solo-io/gloo/issues/668 - allow configuration conneciton settings.
    resolvesIssue: false
    issueLink: https://github.com/solo-io/gloo/issues/668
