name: Gloo Regression Tests
description: configuration to enable make targets

runs:
  using: "composite"
  steps:
  - name: Prep Go Runner
    uses: ./.github/workflows/composite-actions/prep-go-runner
  - name: Install kind
    uses: helm/kind-action@v1.5.0
    with:
      install_only: true
      version: ${{ matrix.kube-version.kind }}
  - uses: azure/setup-kubectl@v3
    id: kubectl
    with:
      version: ${{ matrix.kube-version.kubectl }}
  - uses: azure/setup-helm@v3
    with:
      version: v3.6.3
  - name: Setup test env
    shell: bash
    env:
      KUBE2E_TESTS: ${{ matrix.kube-e2e-test-type }}
      CLUSTER_NAME: 'kind'
      CLUSTER_NODE_VERSION: ${{ matrix.kube-version.node }}
      VERSION: '1.0.0-ci'
    run: ./ci/deploy-to-kind-cluster.sh
  - name: Testing - kube e2e regression tests
    shell: bash
    env:
      SKIP_TEMP_DISABLED: "1"
      KUBE2E_TESTS: ${{ matrix.kube-e2e-test-type }}
      GITHUB_TOKEN: ${{ github.token }}
      VERSION: '1.0.0-ci'
    run: make run-ci-regression-tests
  - uses: testspace-com/setup-testspace@v1
    with:
      domain: solo-io.testspace.com
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
  - name: Push result to Testspace server
    shell: bash
    run: testspace push --verbose "**/junit.xml"
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
  - name: Debug Info
    if: failure()
    shell: bash
    run: |
      # see what's in the cluster if we failed
      kubectl get all -A
      kubectl get configmaps -A
  - name: save results
    if: ${{ failure() }}
    shell: bash
    run: echo '{"url":"https://github.com/solo-io/gloo/actions/runs/${{github.run_id}}",
            "name":"${{matrix.kube-e2e-test-type}}@k8s${{matrix.kube-version.kubectl}}"}' > test-out.json
  - uses: actions/upload-artifact@v3
    if: ${{ failure() }}
    with:
      name: ${{matrix.kube-e2e-test-type}}@k8s${{matrix.kube-version.kubectl}}
      path: test-out.json
      if-no-files-found: warn