apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: passthrough-auth
  namespace: gloo-system
spec:
  configs:
    - passThroughAuth:
        # As of Gloo Edge v1.6.1, grpc is the only passthrough auth method supported
        grpc:
          # Address of the grpc auth server to query
          address: 10.96.2.2
          # Set a connection timeout to external service, default is 5 seconds
          connectionTimeout: 3s