apiVersion: v1
kind: Service
metadata:
  name: example-grpc-auth-service
  labels:
      app: grpc-extauth
spec:
  clusterIP: 10.96.2.2
  ports:
  - port: 9001
    protocol: TCP
  selector:
      app: grpc-extauth