name: Cache

on:
  # We utilize this job to seed the GitHub action cache(s) for the LTS branch
  push:
    branches:
      - 'main'
      - 'v1.**.x'
      - 'gha-cache-**' # for testing

jobs:
  go-modules:
  - name: Check out code into the Go module directory
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
  - name: Cache Go Modules
    runs-on: ubuntu-22.04
    steps:
      - name: Prep Go Runner
        uses: ./.github/workflows/composite-actions/prep-go-runner