name: Cache

on:
  # We utilize this job to seed the GitHub action cache(s) for the LTS branch
  push:
    branches:
      - 'main'
      - 'v1.**.x'
      - 'gha-cache-**'

jobs:
  go-modules-setup:
    name: Setup Go Modules Cache
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Prep Go Runner
      uses: ./.github/workflows/composite-actions/prep-go-runner
    - name: Tidy Go Modules
      run: go mod tidy