name: Cache

on:
  # We utilize this job to seed the GitHub action cache(s) for the LTS branch
  push: {}

jobs:
  go-modules:
    name: Cache Go Modules
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # This is the crucial step
      # The setup-go action has caching built-in,
      # so when this runs, a cache entry will be created, if it does not already exist
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
        id: go