name: Label PR by Kind

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  issues: write

jobs:
  kind-label:
    runs-on: ubuntu-latest
    steps:
    - name: enhancement
      if: contains(github.event.pull_request.description, '/kind enhancement')
      uses: christianvuerings/add-labels@v1
      with:
        labels: |
          kind/enhancement
