name: Istio Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  VERSION: '1.0.0-ci1'
  GITHUB_TOKEN: ${{ github.token }} # necessary to pass upgrade tests

jobs:
  prepare_env:
    name: Prepare Environment
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      should-auto-succeed-istio-tests: ${{ steps.run-strategy.outputs.auto_succeed }}
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - id: checkout-code
        uses: actions/checkout@v3
        with:
          # We require gathering the branch and tag history since we rely on a `git diff`
          # which compares the state of two branches
          fetch-depth: 0
      - id: process-skip-directives
        uses: ./.github/workflows/composite-actions/process-skip-directives
        with:
          base-ref: ${{ github.base_ref }}
      - id: run-strategy
        name: Determine Test Run Strategy
        run: |
          skip_kube_tests=${{ steps.process-skip-directives.outputs.skip-kube-tests }}
          if [[ ! -z $skip_kube_tests && $skip_kube_tests = true ]] ; then
            echo "auto_succeed=true" >> $GITHUB_OUTPUT
          fi

  # TODO(npolshak): Add multiple istio versions to test matrix
  istio_tests:
    name: istio integration tests
    needs: prepare_env
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: [ 'istio-auto', 'gloo-gateway' ]
        kube-version: [ { node: 'v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245', kubectl: 'v1.29.2', kind: 'v0.20.0', helm: 'v3.14.4' } ]
        merge-to-main:
          - ${{ github.event.pull_request.base.ref == 'main' }}
        exclude:
          - merge-to-main: true
            kube-e2e-test-type: upgrade
    steps:
      - uses: actions/checkout@v3
      - id: run-tests
        if: needs.prepare_env.outputs.should-auto-succeed-istio-tests != 'true'
        uses: ./.github/workflows/composite-actions/istio-tests
      - id: auto-succeed-tests
        if: needs.prepare_env.outputs.should-auto-succeed-istio-tests == 'true'
        run: |
          echo "Istio tests auto-succeeded"