name: Nightly

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # necessary to pass upgrade tests

on:
  schedule:
    - cron: "0 5 * * 1-5" # weekdays @ 00:00 EST, run tests against latest dev
    - cron: "6 6 * * 1"   # monday   @ 01:06 EST, run expanded tests against v1.13.x 
    - cron: "7 7 * * 1"   # monday   @ 02:07 EST, run expanded tests against v1.12.x
    - cron: "8 8 * * 1"   # monday   @ 03:08 EST, run expanded tests against v1.11.x
    - cron: "9 9 * * 1"   # monday   @ 04:09 EST, run expanded tests against v1.10.x
  workflow_dispatch:
jobs:
  regression_tests_latest_dev:
    name: latest dev regression tests
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 5 * * 1-5'
    runs-on: ubuntu-22.04
    # Previously, there was an environment variable, RELEASED_VERSION="LATEST" set.  This made use of some internal code:
    #       https://github.com/solo-io/gloo/blob/master/test/kube2e/util.go#L229-L241
    # which modified our testing process to pull the latest beta release.
    #
    # NOW, however, running this job is the same as normal CI.  (building a local chart, then using it)
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: ['gateway', 'gloo', 'ingress', 'helm', 'gloomtls', 'glooctl', 'upgrade']
        kube-version: [{ node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7',  kind: 'v0.17.0'}]
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/regression-tests

  regression_tests_13:
    name: v1.13.x regression tests
    if: github.event.schedule == '6 6 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: ['gateway', 'gloo', 'ingress', 'helm', 'gloomtls', 'glooctl', 'upgrade']
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: v1.13.x
    - uses: ./.github/actions/regression-tests

  regression_tests_12:
    name: v1.12.x regression tests
    if: github.event.schedule == '7 7 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: ['gateway', 'gloo', 'ingress', 'helm', 'gloomtls', 'glooctl', 'upgrade']
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: v1.12.x
    - uses: ./.github/actions/regression-tests

  regression_tests_11:
    name: v1.11.x regression tests
    if: github.event.schedule == '8 8 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: ['gateway', 'gloo', 'ingress', 'helm', 'gloomtls', 'glooctl', 'upgrade']
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: v1.11.x
    - uses: ./.github/actions/regression-tests

  regression_tests_10:
    name: v1.10.x regression tests
    if: github.event.schedule == '9 9 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: ['gateway', 'gloo', 'ingress', 'helm', 'gloomtls', 'glooctl', 'upgrade']
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: v1.10.x
    - uses: ./.github/actions/regression-tests

  publish_results:
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    needs: [ regression_tests_latest_dev, regression_tests_13, regression_tests_12, regression_tests_11, regression_tests_10 ] 
    steps:
      - uses: actions/checkout@v3
      - name: compute-preamble
        id: compute-preamble
        shell: bash
        run: |
          echo "SLACK_CHANNEL=C04CJMXAH7A" >> $GITHUB_ENV     #edge-nightly-results by default
          if [[ ${{github.event_name == 'workflow_dispatch'}} = true ]]; then
            preamble="Gloo OSS nightlies (manual run)"
            echo "SLACK_CHANNEL=C0314KESVNV" >> $GITHUB_ENV   #slack-integration-testing if manually run
          elif [[ ${{github.event.schedule == '9 9 * * 1'}} = true ]]; then
              preamble="Gloo OSS weeklies (v1.10.x)"
          elif [[ ${{github.event.schedule == '8 8 * * 1'}} = true ]]; then
              preamble="Gloo OSS weeklies (v1.11.x)"
          elif [[ ${{github.event.schedule == '7 7 * * 1'}} = true ]]; then
              preamble="Gloo OSS weeklies (v1.12.x)"
          elif [[ ${{github.event.schedule == '6 6 * * 1'}} = true ]]; then
              preamble="Gloo OSS weeklies (v1.13.x)"
          elif [[ ${{github.event.schedule == '0 5 * * 1-5'}} = true ]]; then
              preamble="Gloo OSS nightlies (dev)"
          fi

          echo "Setting PREAMBLE as $preamble"
          echo "::set-output name=preamble::$(echo $preamble)"
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.2
      - uses: actions/download-artifact@v3
      - name: send slack message
        env:
          PARENT_JOB_URL: https://github.com/solo-io/gloo/actions/runs/${{github.run_id}} # parent job hyperlink
          PREAMBLE: ${{ steps.compute-preamble.outputs.preamble }}  # text to hyperlink at start of slack message
          SLACKBOT_BEARER: ${{ secrets.SLACKBOT_BEARER }}
          SLACK_CHANNEL: "C04CJMXAH7A"  #edge-nightly-results
          # SLACK_CHANNEL: "C0314KESVNV"  #slack-integration-testing
        run: |
          test_results="$(cat */test-out.json | jq -c --slurp .)"
          echo $test_results
          go run .github/workflows/helpers/notify-from-json.go $test_results