name: GGII Tests
on: pull_request

jobs:
  test_gloo_gateway2:
    name: Build and Test Gloo Gateway 2
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Build
      run: go build -v ./projects/gateway2/... ./projects/gloo/cli/cmd
    - name: Install utils for env tests
      run: make -C ./projects/gateway2/ install-go-tools
    - name: Test with the Go CLI
      run: go test ./projects/gateway2/...

  conformance:
    name: Run Gateway api conformance tests
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Install kind
      uses: helm/kind-action@v1.5.0
      with:
        install_only: true
        version: v0.20.0
    - name: Set up cluster and helm chart
      run: ./ci/kind/setup-kind.sh
    - name: Additional cluster setup
      run: ./projects/gateway2/kind.sh
    - name: Install Gloo Gateway
      run: helm upgrade -i -n gloo-system gloo ./_test/gloo-1.0.0-ci.tgz --create-namespace -f ./projects/gateway2/tests/conformance/test-values.yaml
    - name: Pre-test cleanup of resources
      run: kubectl delete rs --all
    - name: Test Conformance
      run: make -C ./projects/gateway2/ conformance
