name: pull_request

on:
  push:
    branches:
    - 'master'
  pull_request: {}

env:
  TAGGED_VERSION: ${{github.event.release.tag_name || '' }}

jobs:
  test:
    name: regression-tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - uses: engineerd/setup-kind@v0.3.0
    - name: Install Protoc
      uses: arduino/setup-protoc@v1.1.0
      with:
        version: '3.6.1'
    - uses: azure/setup-kubectl@v1
      id: kubectl
      with:
        version: 'v1.18.0'
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: azure/setup-helm@v1
      with:
        version: v3.2.0
    - name: Setup env
      env:
        # version for tag tags
        VERSION: kind
      # not sure if we need all binaries below. can remove if we don't.
      run: |
        curl -sSL https://github.com/istio/istio/releases/download/1.5.1/istio-1.5.1-linux.tar.gz | tar -xzf - istio-1.5.1/bin/istioctl
        export PATH=$PWD/istio-1.5.1/bin:$PWD/linux-amd64:$PATH
        go get -u github.com/onsi/ginkgo/ginkgo
        docker pull kennship/http-echo@sha256:144322e8e96be2be6675dcf6e3ee15697c5d052d14d240e8914871a2a83990af
        kind load docker-image kennship/http-echo@sha256:144322e8e96be2be6675dcf6e3ee15697c5d052d14d240e8914871a2a83990af --nodes kind-control-plane
        docker pull soloio/testrunner@sha256:123bce9529bba376d9dad9e0d162c3627feec1214d5a9a64a15dee582e6676d5
        kind load docker-image soloio/testrunner@sha256:123bce9529bba376d9dad9e0d162c3627feec1214d5a9a64a15dee582e6676d5 --nodes kind-control-plane
        make update-deps
        make build-kind-assets
    - name: Testing - cluster lock
      env:
        RUN_KUBE2E_TESTS: '1'
        CLUSTER_LOCK_TESTS: '1'
      run: |
        ginkgo -r -failFast -trace -progress -race -compilers=4 -failOnPending -noColor test/kube2e
    - name: Testing - no cluster lock
      env:
        RUN_KUBE2E_TESTS: '1'
      run: |
        ginkgo -r -failFast -trace -progress -race -compilers=4 -failOnPending -noColor test/kube2e
    - name: Debug Info
      if: failure()
      run: |
        # see what's in the cluster if we failed
        kubectl get all -A
        kubectl get configmaps -A
