name: CI
on: pull_request

env:
  VERSION: '1.0.0-ci'
  GITHUB_TOKEN: ${{ github.token }} # necessary to pass upgrade tests

jobs:
  prepare_env:
    name: Prepare Environment
    runs-on: ubuntu-22.04
    outputs:
      should-run-regression-tests: ${{ steps.regression-tests.outputs.run_value }}
      should-auto-succeed-regression-tests: ${{ steps.regression-tests.outputs.auto_succeed }}
    steps:
    - name: Cancel Previous Actions
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - id: is-draft-pr
      name: Process draft Pull Requests
      if: ${{ github.event.pull_request.draft }}
      run: echo "value=true" >> $GITHUB_OUTPUT
    - id: checkout-code
      uses: actions/checkout@v3
      with:
        # We require gathering the branch and tag history since we compare
        fetch-depth: 0
    - uses: ./.github/workflows/composite-actions/prep-go-runner
    - id: process-skip-directives
      uses: ./.github/workflows/composite-actions/process-skip-directives
    - id: regression-tests
      name: Determine Test Run Strategy
      run: |
        should_run=true
        should_auto_succeed=false

        is_draft_pr=${{ steps.is-draft-pr.outputs.value }}
        if [[ ! -z $is_draft_pr && $is_draft_pr = true ]] ; then
          should_run=false
        fi

        skip_kube_tests=${{ steps.process-skip-directives.outputs.skip-kube-tests }}
        if [[ ! -z $skip_kube_tests && $skip_kube_tests = true ]] ; then
          should_auto_succeed=true
        fi

        echo "Run strategy: Should run? $should_run. Should auto-succeed? $should_auto_succeed"
        echo "run_value=$should_run" >> $GITHUB_OUTPUT
        echo "auto_succeed=$should_auto_succeed" >> $GITHUB_OUTPUT

  regression_tests:
    name: k8s regression tests (${{matrix.kube-e2e-test-type}})
    needs: prepare_env
    runs-on: ubuntu-22.04
    if: needs.prepare_env.outputs.should-run-regression-tests == 'true'
    strategy:
      fail-fast: false
      matrix:
        # upgrade tests are run on LTS but not on main branch, for main they are run nightly
        # this is the github action version of ternary op
        kube-e2e-test-type: [ 'gateway', 'gloo', 'ingress', 'helm', 'gloomtls', 'glooctl', 'istio', 'upgrade']
        kube-version: [ { node: 'v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f', kubectl: 'v1.26.3', kind: 'v0.18.0', helm: 'v3.11.2' } ]
        merge-to-main:
          - ${{ github.event.pull_request.base.ref == 'main' }}
        exclude:
          - merge-to-main: true
            kube-e2e-test-type: upgrade
    steps:
    - uses: actions/checkout@v3
    - id: run-tests
      if: needs.prepare_env.outputs.should-auto-succeed-regression-tests == 'false'
      uses: ./.github/workflows/composite-actions/regression-tests
    - id: auto-succeed-tests
      if: needs.prepare_env.outputs.should-auto-succeed-regression-tests == 'true'
      run: |
        echo "Regression tests auto-succeeded"