name: CI
on: pull_request

env:
  VERSION: '1.0.0-ci'
  GITHUB_TOKEN: ${{ github.token }} # necessary to pass upgrade tests

jobs:
  prepare_env:
    name: Prepare Environment
    runs-on: ubuntu-22.04
    outputs:
      should-run-regression-tests: ${{ steps.regression-tests.outputs.run_value }}
      should-pass-regression-tests: ${{ steps.regression-tests.outputs.pass_value }}
    steps:
    - name: Cancel Previous Actions
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - id: is-draft-pr
      name: Process draft Pull Requests
      if: ${{ github.event.pull_request.draft }}
      run: echo "value=true" >> $GITHUB_OUTPUT
    - id: signal-ci-comment
      name: Process comments on Pull Request to signal CI
      if:  ${{ github.event.issue.pull_request }}
      run: echo "value=${{ contains(github.event.comment.body, '/sig-ci') }}" >> $GITHUB_OUTPUT
    - id: skip-ci-comment
      name: Process comments on Pull Request to skip CI
      if: ${{ github.event.issue.pull_request }}
      run: echo "value=${{ contains(github.event.comment.body, '/skip-ci') }}" >> $GITHUB_OUTPUT
    - id: regression-tests
      name: Determine how to run regression tests
      run: |
        should_run=true

        is_draft_pr=${{ steps.is-draft-pr.outputs.value }}
        if [[ ! -z $is_draft_pr && $is_draft_pr = true ]] ; then
          should_run=false
        fi

        pr_comment_signal=${{ steps.signal-ci-comment.outputs.value }}
        if [[ ! -z $pr_comment_signal && $pr_comment_signal = true ]] ; then
          should_run=true
        fi

        pr_comment_skip=${{ steps.skip-ci-comment.outputs.value }}
        if [[ ! -z $pr_comment_skip && $pr_comment_skip = true ]] ; then
          should_run=false
        fi

        echo "Should run regression tests? $should_run"
        echo "run_value=$should_run" >> $GITHUB_OUTPUT

  regression_tests:
    name: k8s regression tests (${{matrix.kube-e2e-test-type}})
    needs: prepare_env
    runs-on: ubuntu-22.04
    if: needs.prepare_env.outputs.should-run-regression-tests == 'true'
    strategy:
      fail-fast: false
      matrix:
        # upgrade tests are run on LTS but not on main branch, for main they are run nightly
        # this is the github action version of ternary op
        kube-e2e-test-type: [ 'gateway', 'gloo', 'ingress', 'helm', 'gloomtls', 'glooctl', 'istio', 'upgrade']
        kube-version: [ { node: 'v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f', kubectl: 'v1.26.3', kind: 'v0.18.0', helm: 'v3.11.2' } ]
        merge-to-main:
          - ${{ github.event.pull_request.base.ref == 'main' }}
        exclude:
          - merge-to-main: true
            kube-e2e-test-type: upgrade
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/composite-actions/regression-tests
