name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  regression_tests:
    name: k8s regression tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        kube-e2e-test-type: ['gateway', 'ingress', 'knative', 'helm', 'gloomtls', 'glooctl', 'eds']
    steps:
    - name: Cancel Previous Actions
      uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ github.token }}
    - name: Set up Go 1.16.3
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: engineerd/setup-kind@v0.5.0
      with:
        skipClusterCreation: true
    - uses: azure/setup-kubectl@v1
      id: kubectl
      with:
        version: 'v1.18.0'
    - uses: azure/setup-helm@v1
      with:
        version: v3.2.0
    - name: Setup test env
      env:
        KUBE2E_TESTS: ${{ matrix.kube-e2e-test-type }}
      run: |
        ./ci/kind.sh
    - name: Testing - kube e2e regression tests
      env:
        KUBE2E_TESTS: ${{ matrix.kube-e2e-test-type }}
      run: |
        make run-ci-regression-tests
    - uses: testspace-com/setup-testspace@v1
      with:
        domain: solo-io.testspace.com
      if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    - name: Push result to Testspace server
      run: |
        testspace push --verbose "**/junit.xml"
      if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    - name: Debug Info
      if: failure()
      run: |
        # see what's in the cluster if we failed
        kubectl get all -A
        kubectl get configmaps -A
