name: Regression Test Setup
on: pull_request
jobs:
  regression_test_setup:
    name: Regression Test Setup
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1442930
          access_token: ${{ github.token }}
      - name: Setup Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: engineerd/setup-kind@v0.4.0
        with:
          name: kind
      - uses: azure/setup-kubectl@v1
        id: kubectl
        with:
          version: 'v1.18.0'
      - name: Setup test env
        run: |
          ./ci/kind.sh
      - name: Debug Info
        if: failure()
        run: |
          # see what's in the cluster if we failed
          kubectl get all -A
          kubectl get configmaps -A
