name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:

env:
  VERSION: '1.0.0-ci'

jobs:
  notify_slack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.2
      - uses: actions/download-artifact@v3
      - name: Set pull_request_url
        run: |
          echo "pull_request_url=$(cat ${{ github.event_path }} | jq --raw-output .pull_request._links.html.href)" >> $GITHUB_ENV
          echo ${{ env.pull_request_url }}
      - name: Set direct_message_id
        shell: bash
        run: |
          echo "direct_message_id=$(cat ./.github/workflows/notify-on-regression-failure-list.json | jq -r '."${{ github.actor }}"')" >> $GITHUB_ENV
          echo ${{ env.direct_message_id }}
      - name: send slack message
        env:
          PARENT_JOB_URL: ${{ env.pull_request_url }}       # parent job hyperlink
          PREAMBLE: "Your recent Gloo PR"                   # text to hyperlink at start of slack message
          SLACK_CHANNEL: ${{ env.direct_message_id }}       # DM to the user who ran CI
          SLACKBOT_BEARER: ${{ secrets.SLACKBOT_BEARER }}
        run: |
          test_results="$(cat */test-out.json | jq -c --slurp .)"
          echo $test_results
          go run .github/workflows/helpers/notify-from-json.go $test_results
