name: Actions Testing
on:
  workflow_dispatch:
jobs:
  regression_tests:
    name: k8s regression tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: ['gateway', 'gloo', 'ingress', 'helm', 'gloomtls', 'glooctl', 'upgrade']
    steps:
      - name: run test
        run: echo ${{ matrix.kube-e2e-test-type }}
      - name: save results
        run: echo '{"url":"https://github.com/solo-io/gloo/actions/runs/${{github.run_id}}",
                "name":"${{matrix.kube-e2e-test-type}}"}' > test-out.json
      - uses: actions/upload-artifact@v3
      # if: ${{ failure() }} TODO: uncomment
        with:
          name: ${{ matrix.kube-e2e-test-type }}
          path: test-out.json
          if-no-files-found: warn

  check-matrix:
    runs-on:  ubuntu-22.04
    needs: [ regression_tests ]
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          results="$(cat */test-out.json | jq -c --slurp .)"
          echo $results