changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo/issues/6470
    description: Expose `extensions.filters.network.http_connection_manager.v3.HttpConnectionManager.InternalAddressConfig`

