{{- if .Values.controlPlane.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gloo-gateway.controlPlane.fullname" . }}
  labels:
    app: gloo
    {{- include "gloo-gateway.controlPlane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gloo-gateway.controlPlane.selectorLabels" . | nindent 4 }}
{{- end }}